Repository ecmwf/anemoi-graphs, pull requests merged in 2024-11, with the labels that each got.

#76 Remove docconvert from .pre-commit-config.yaml
  .pre-commit-config.yaml
Labels: no changelog

#73 missing copyrigths
  docs/conf.py
  pyproject.toml
  src/anemoi/graphs/__init__.py
  src/anemoi/graphs/__main__.py
  src/anemoi/graphs/commands/__init__.py
  src/anemoi/graphs/edges/__init__.py
  src/anemoi/graphs/generate/__init__.py
  src/anemoi/graphs/nodes/__init__.py
  src/anemoi/graphs/nodes/builders/__init__.py
  src/anemoi/graphs/plotting/__init__.py
Labels: no changelog

#53 feature: support icon graphs
  CHANGELOG.md
  docs/graphs/node_coordinates/icon_mesh.rst
  pyproject.toml
  src/anemoi/graphs/edges/__init__.py
  src/anemoi/graphs/edges/builder.py
  src/anemoi/graphs/generate/icon_mesh.py
  src/anemoi/graphs/generate/utils.py
  src/anemoi/graphs/nodes/__init__.py
  src/anemoi/graphs/nodes/builders/from_icon.py
  tests/nodes/test_icon.py
Labels: contributor

#78 Add scikit-learn dependency to pyproject.toml
  pyproject.toml
Labels: contributor, no changelog

#79 Fix/Voronoi issue
  CHANGELOG.md
  src/anemoi/graphs/nodes/attributes.py
Labels: contributor

#71 [feature] support post-processors
  CHANGELOG.md
  src/anemoi/graphs/create.py
  src/anemoi/graphs/processors/__init__.py
  src/anemoi/graphs/processors/post_process.py
  tests/conftest.py
  tests/processors/test_post_process.py
Labels: enhancement

#70 [feature] allow multiple edge builders
  CHANGELOG.md
  src/anemoi/graphs/create.py
  src/anemoi/graphs/edges/builder.py
  src/anemoi/graphs/nodes/attributes.py
  src/anemoi/graphs/utils.py
  tests/conftest.py
  tests/test_utils.py
Labels: enhancement

#42 Documentation: Limited Area Modeling
  CHANGELOG.md
  docs/cli/inspect.rst
  docs/graphs/edge_attributes.rst
  docs/graphs/edges.rst
  docs/graphs/edges/cutoff.rst
  docs/graphs/edges/knn.rst
  docs/graphs/edges/multi_scale.rst
  docs/graphs/edges/tri_refined_edges.csv
  docs/graphs/introduction.rst
  docs/graphs/node_attributes.rst
  docs/graphs/node_attributes/boolean_operations.rst
  docs/graphs/node_attributes/weights.rst
  docs/graphs/node_attributes/zarr_attribute.rst
  docs/graphs/node_coordinates.rst
  docs/graphs/node_coordinates/healpix.rst
  docs/graphs/node_coordinates/hex_refined_icosahedron.rst
  docs/graphs/node_coordinates/icon_mesh.rst
  docs/graphs/node_coordinates/npz_file.rst
  docs/graphs/node_coordinates/tri_nodes.csv
  docs/graphs/node_coordinates/tri_refined_icosahedron.rst
  docs/graphs/node_coordinates/zarr_dataset.rst
  docs/graphs/yaml/attributes_boolean_operation.yaml
  docs/graphs/yaml/attributes_cutout.yaml
  docs/graphs/yaml/attributes_nonmissingzarr.yaml
  docs/graphs/yaml/attributes_weights.yaml
  docs/index.rst
  docs/modules/edge_builder.rst
  docs/modules/node_attributes.rst
  docs/modules/node_builder.rst
  docs/modules/post_processor.rst
  docs/usage/getting_started.rst
  docs/usage/limited_area.rst
  docs/usage/yaml/cutout_zarr.yaml
  docs/usage/yaml/global.yaml
  docs/usage/yaml/global_with-attrs.yaml
  docs/usage/yaml/global_wo-proc.yaml
  docs/usage/yaml/lam_nodes_wo_boundary.yaml
  docs/usage/yaml/limited_area_nodes.yaml
  docs/usage/yaml/nodes.yaml
  src/anemoi/graphs/edges/attributes.py
  src/anemoi/graphs/inspect.py
Labels: documentation

#81 warn AreaWeights filling
  src/anemoi/graphs/nodes/attributes.py
Labels: no changelog

#83 Fix/deprecated config file
  CHANGELOG.md
  src/anemoi/graphs/create.py
  src/anemoi/graphs/nodes/attributes.py
Labels: no changelog

#85 fix: use update_graph without attrs_cfg instead register_edges
  src/anemoi/graphs/create.py
  src/anemoi/graphs/nodes/builders/base.py
  src/anemoi/graphs/nodes/builders/from_file.py
  src/anemoi/graphs/nodes/builders/from_healpix.py
  src/anemoi/graphs/nodes/builders/from_icon.py
Labels: no changelog
